<?php

namespace App\Repository;

use App\Entity\Ingredient;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param array $ids
     * @return Ingredient[]
     */
    public function findByExcludedIds(array $ids): array
    {
        if (empty($ids)) {
            return [];
        }

        $queryBuilder = $this->createQueryBuilder('ingredient');

        $query = $queryBuilder->where($queryBuilder->expr()->notIn('ingredient.id', $ids))
            ->getQuery();

        return $query->getResult();
    }
}
