<?php

namespace App\Repository;

/**
 * PizzaIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzaIngredientsRepository extends \Doctrine\ORM\EntityRepository
{
}
