<?php

namespace App\Repository;

/**
 * PizzaIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzaIngredientRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll( array $orderBy = null )
    {
        return $this->findBy([], ['ingredientOrder' => 'ASC']);
    }
}
